title: Black Sea the Movie
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 1
color:
  saturation: 0.2801673
  brandStrength: 0.07825568
  lightness: 0.8787335
  brandColors:
    - '#11100B'
    - '#7D756D'
    - '#3D321F'
    - '#D5CBC2'
    - '#A99C93'
  rhythmicContrast: 0.7855436
layout_spectrum: 0.449195109307766
name: Black Sea
